In [43]:
import pandas as pd
import numpy as np
from sklearn.pipeline import FeatureUnion

In [44]:
df = pd.read_csv('Higher Institutions.csv')
df

Name           Ownership  \
0       Federal College of Education (Technical), Asaba  Federal Government   
1                   Federal College of Education,  Kano  Federal Government   
2           Federal College of Education (Special), Oyo  Federal Government   
3                        College of Education,  Gindiri    State Government   
4                           College of Education, Hong     State Government   
...                                                 ...                 ...   
1043      Umuebe Farm College, Abakililki, Ebonyi State             Private   
1044         Unival Institute of Technology, Benin City             Private   
1045  UTAGBA-UNO Vocational Enterprise Institute, is...             Private   
1046                 Yenagoa Enterprise School, Yenagoa             Private   
1047  Young Men Christian Association (YMCA) Vocatio...             Private   

                   Category  Year of Establishment  
0      College of Education                   1987  
1      College of Education                   1961  
2      College of Education                   1977  
3      College of Education                   1980  
4      College of Education                   1970  
...                     ...                    ...  
1043  Specialized Institute                   2010  
1044  Specialized Institute                   2015  
1045  Specialized Institute                   2009  
1046  Specialized Institute                   2015  
1047  Specialized Institute                   2012  

[1048 rows x 4 columns]

In [47]:
a = df['Name']
b = df['Ownership']
c = df['Category']
y = df['Year of Establishment'].values

In [48]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
a_lower = [text.lower() for text in a]
b_lower = [text.lower() for text in b]
c_lower = [text.lower() for text in c]

In [76]:
cv_a = CountVectorizer()
cv_b = CountVectorizer()
cv_c = CountVectorizer()

In [77]:
a_transformed = cv_a.fit_transform(a_lower)
b_transformed = cv_b.fit_transform(b_lower)
c_transformed = cv_c.fit_transform(c_lower)

In [78]:
X = np.hstack((a_transformed.toarray(), b_transformed.toarray(), c_transformed.toarray()))

In [79]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [91]:
from sklearn import svm
model = svm.SVC(kernel='linear')
model.fit(X_train,y_train)

SVC(kernel='linear')

In [92]:
user1 = input("Name: ").lower()
user2 = input("Ownership: ").lower()
user3 = input("Category: ").lower()
data_a = cv_a.transform([user1])
data_b = cv_b.transform([user2])
data_c = cv_c.transform([user3])
data = np.hstack((data_a.toarray(), data_b.toarray(), data_c.toarray()))
y_pred = model.predict(data)
print(y_pred)

Name: University of Port Harcourt
Ownership: Federal University
Category: University
[1975]


In [99]:
# from sklearn.metrics import r2_score
# r2_score(y_test, y_pred)

In [61]:
print(y_test.shape)


(315,)


In [62]:
print(y_pred.shape)

(1,)


In [63]:
y_test = y_test.reshape(-1)
y_pred = y_pred.reshape(-1)

In [64]:
print(y_pred.shape)

(1,)


In [65]:
print(y_test.shape)

(315,)


In [93]:
print(X_train)

[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


In [94]:
print(X_test)

[[0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]]


In [95]:
print(data_a)

  (0, 921)	1
  (0, 1489)	1
  (0, 1702)	1
  (0, 2004)	1


In [96]:
print(data_b)

  (0, 0)	1


In [97]:
print(data_c)

  (0, 17)	1


In [98]:
data

array([[0, 0, 0, ..., 0, 1, 0]], dtype=int64)